from django.db import models

# Create your models here.
class Batting(models.Model):
    name = models.CharField(max_length=255)
    age = models.IntegerField()
    position = models.CharField(max_length=3)
    games = models.IntegerField()
    plate_appearance = models.IntegerField()
    at_bat = models.IntegerField()
    runs = models.IntegerField()
    hits = models.IntegerField()
    doubles = models.IntegerField()
    triples = models.IntegerField()
    homeruns = models.IntegerField()
    rbi = models.IntegerField()
    steals = models.IntegerField()
    caught_stealing = models.IntegerField()
    walks = models.IntegerField()
    strikeouts = models.IntegerField()
    avg = models.FloatField()
    obp = models.FloatField()
    slg = models.FloatField()
    ops_percentage = models.FloatField()
    ops = models.IntegerField()
    total_base = models.IntegerField()
    gidp = models.IntegerField()
    hbp = models.IntegerField()
    sac_hit = models.IntegerField()
    sac_fly = models.IntegerField()
    ibb = models.IntegerField()

class Pitching(models.Model):
    name = models.CharField(max_length=255)
    age = models.IntegerField()
    position = models.CharField(max_length=3)
    wins = models.CharField(max_length=10)
    loss = models.CharField(max_length=10)
    win_loss = models.CharField(max_length=10)
    era = models.CharField(max_length=10)
    games = models.CharField(max_length=10)
    games_started = models.CharField(max_length=10)
    games_finished = models.CharField(max_length=10)
    complete_games = models.CharField(max_length=10)
    shutout = models.CharField(max_length=10)
    saves = models.CharField(max_length=10)
    ip = models.CharField(max_length=10)
    hits = models.CharField(max_length=10)
    runs = models.CharField(max_length=10)
    earned_runs = models.CharField(max_length=10)
    hr = models.CharField(max_length=10)
    walks = models.CharField(max_length=10)
    ibb = models.CharField(max_length=10)
    strikeouts = models.CharField(max_length=10)
    hbp = models.CharField(max_length=10)
    balks = models.CharField(max_length=10)
    wild_pitch = models.CharField(max_length=10)
    batters_faced = models.CharField(max_length=10)
    erav = models.CharField(max_length=10)
    fip = models.CharField(max_length=10)
    whip = models.CharField(max_length=10)
    h9 = models.CharField(max_length=10)
    hr9 = models.CharField(max_length=10)
    bb9 = models.CharField(max_length=10)
    so9 = models.CharField(max_length=10)
    sow = models.CharField(max_length=10)
