# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 16:21
from __future__ import unicode_literals

from django.db import migrations
import csv

def add_all_data(apps, schema_editor):
    Batting = apps.get_model('app', 'Batting')
    Pitching = apps.get_model('app', 'Pitching')

    with open('hitter.csv') as open_file:
        reader = csv.reader(open_file)
        for row in reader:
            Batting.objects.create(id=row[0], position=row[1], name=row[2], age=row[3], games=row[4], plate_appearance=row[5], at_bat=row[6],\
                                   runs=row[7], hits=row[8], doubles=row[9], triples=row[10], homeruns=row[11], rbi=row[12], steals=row[13],\
                                   caught_stealing=row[14], walks=row[15], strikeouts=row[16], avg=row[17], obp=row[18], slg=row[19], ops_percentage=row[20],\
                                   ops=row[21], total_base=row[22], gidp=row[23], hbp=row[24], sac_hit=row[25], sac_fly=row[26], ibb=row[27])

        # raise Exception ("BOOM!")

    with open('pitcher.csv') as open_file:
        reader = csv.reader(open_file)
        for row in reader:
            Pitching.objects.create(id=row[0], position=row[1], name=row[2], age=row[3], wins=row[4], loss=row[5], win_loss=row[6],\
                                   era=row[7], games=row[8], games_started=row[9], games_finished=row[10], complete_games=row[11], shutout=row[12], saves=row[13],\
                                   ip=row[14], hits=row[15], runs=row[16], earned_runs=row[17], hr=row[18], walks=row[19], ibb=row[20],\
                                   strikeouts=row[21], hbp=row[22], balks=row[23], wild_pitch=row[24], batters_faced=row[25], erav=row[26],\
                                   fip=row[27], whip=row[28], h9=row[29], hr9=row[30], bb9=row[31], so9=row[32], sow=row[33])

        # raise Exception ("BOOM!")

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_all_data)
    ]
